-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/quantized_bpf/Filter.vhd
-- Created: 2025-05-11 09:46:50
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out_rsvd                      ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Filter
-- Source Path: quantized_bpf/Filter
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In_rsvd                           :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
        ce_out                            :   OUT   std_logic;
        Out_rsvd                          :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En8
        );
END Filter;


ARCHITECTURE rtl OF Filter IS

  -- Component Declarations
  COMPONENT filter_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_const_rate                  :   IN    std_logic;
          filter_in                       :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          filter_out                      :   OUT   std_logic_vector(11 DOWNTO 0)  -- sfix12_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : filter_block
    USE ENTITY work.filter_block(rtl);

  -- Signals
  SIGNAL filter_out1                      : std_logic_vector(11 DOWNTO 0);  -- ufix12

BEGIN
  u_filter : filter_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_const_rate => clk_enable,
              filter_in => In_rsvd,  -- sfix12
              filter_out => filter_out1  -- sfix12_En8
              );

  ce_out <= clk_enable;

  Out_rsvd <= filter_out1;

END rtl;

