-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/quantized_bpf/Filter_pkg.vhd
-- Created: 2025-05-11 09:46:50
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Filter_pkg IS
  TYPE vector_of_signed12 IS ARRAY (NATURAL RANGE <>) OF signed(11 DOWNTO 0);
END Filter_pkg;

